name: dsci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib=3.8.3
  - numpy=1.26.4
  - scipy=1.12.0
  - pandas=2.2.1
  - rise=5.7.1
  - jupyter=1.0.0
  - jupyterlab=4.1.5
  - jupytext=1.16.1
  - patsy=0.5.6
  - scikit-learn=1.4.2
