name: dsci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - matplotlib=3.10.1
  - numpy=2.2.3
  - scipy=1.15.2
  - pandas=2.2.3
  - jupyter=1.1.1
  - jupyterlab=4.3.5
  - jupytext=1.16.7
  - scikit-learn=1.6.1
  - patsy=1.0.1
  - rise=5.7.1
