name: dsci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib=3.7.1
  - numpy=1.24.2
  - scipy=1.10.1
  - pandas=1.5.3
  - rise=5.7.1
  - jupyter=1.0.0
  - jupyterlab=3.5.0
  - jupytext=1.14.5
  - patsy=0.5.3
